"""empty message

Revision ID: 51e9f9225413
Revises:
Create Date: 2025-05-19 22:26:20.939746

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "51e9f9225413"  # pragma: allowlist secret
down_revision = None  # pragma: allowlist secret
branch_labels = None  # pragma: allowlist secret
depends_on = None  # pragma: allowlist secret


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "beer",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("brand", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order",
        sa.Column(
            "store_type",
            sa.Enum(
                "CORPORATE",
                "DELIVERY",
                "DOWNTOWN",
                "LATE_NIGHT",
                "MALL",
                name="storetype",
            ),
            nullable=False,
        ),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "total_amount", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("customer_name", sa.String(), nullable=True),
        sa.Column("customer_email", sa.String(), nullable=True),
        sa.Column("customer_phone", sa.String(), nullable=True),
        sa.Column("delivery_address", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pizza",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_beer",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("beer_id", sa.UUID(), nullable=False),
        sa.Column(
            "quantity", sa.Numeric(precision=10, scale=0), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["beer_id"],
            ["beer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_pizza",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("pizza_id", sa.UUID(), nullable=False),
        sa.Column(
            "quantity", sa.Numeric(precision=10, scale=0), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pizza_id"],
            ["pizza.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_pizza")
    op.drop_table("order_beer")
    op.drop_table("pizza")
    op.drop_table("order")
    op.drop_table("beer")
    # ### end Alembic commands ###
