flowchart LR
    BL1["Component Level 1"] --> BL2["Component Level 2"] --> BL3["Component Level 3"]
    style BL1 fill:#306998,stroke:#E0E0E0,stroke-width:2px,color:#E0E0E0
    style BL2 fill:#306998,stroke:#E0E0E0,stroke-width:2px,color:#E0E0E0
    style BL3 fill:#306998,stroke:#E0E0E0,stroke-width:2px,color:#E0E0E0
